baseURL = "https://averydriscoll.github.io"  # Replace with your actual username
languageCode = "en-us"
title = "Avery Driscoll"
theme = "cleanwhite"

paginate = 0
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
name = "Avery Driscoll"

[params]
header_image = "img/home-bg.jpg"
SEOTitle = "Avery Driscoll | Research Website"
description = "Agriculture and climate change"
keyword = "agriculture, climate change, soil and crop science, data science"
url = "https://averydriscoll.github.io"  # Replace with your username
baseurl = "https://averydriscoll.github.io"  # Replace with your username

# Sidebar settings
sidebar_about_description = "Academic researcher interested in [your field]. Welcome to my website where I share my research, data, and outreach activities."
sidebar_avatar = "img/avatar.jpg"  # You can add a profile photo later

# Social media links (optional - remove # to enable)
# twitter_username = "yourusername"
# github_username = "yourusername"  
# facebook_username = "yourusername"
# linkedin_username = "yourusername"

# Feature settings
featured_tags = false
featured_condition_size = 0
bookmark_tag = "bookmark"
omit_categories = true

# Analytics (optional)
# ba_track_id = ""
# [services.googleAnalytics]
# id = ""

# Comments (optional)
# [services.disqus]
# shortname = ""

# Search (optional)
algolia_search = false

# Reward (optional)
reward = false

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "github"
lineNos = false

# Menu configuration - this replaces the default "News" and "All posts" buttons

[[menu.main]]
name = "Research"
url = "/research/"
weight = 3

[[menu.main]]
name = "Data"
url = "/data/"
weight = 4

[[menu.main]]
name = "Outreach"
url = "/outreach/"
weight = 5

[[menu.main]]
name = "Bio"
url = "/bio/"
weight = 2

